---
title: "Figure 4"
author: "Aleix Obiol"
date: "2022-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('scripts/aux_functions.R')
```

## Read files

```{r}
quantification_sp_tmm_dfs_sp25 <-  
  readRDS('data/quantification/species52/quantification_sp-level_tmm_species25.rds')

metadata <- 
  readRDS('data/metadata/metadata.rds')

eukprot_tax <- 
  read_tsv('data/taxonomy/EukProt-v3.1_SAGs_tax.txt')

trophic_modes_final_species <- 
  read_tsv('data/aux/species25_trophic-modes.txt')

trophic_colors <- 
  c(Heterotroph = 'darkgoldenrod1',
    Mixotroph = 'lightsalmon3',
    Phototroph = '#4AC16DFF')
```

## Figure 4

```{r}
sp_selection_exp <- 
  experiment_set_names() %>% 
  map(~ quantification_sp_tmm_dfs_sp25[[.x]] %>%
        group_by(EukProt_ID) %>% 
        summarise(max = max(Abundance)) %>%
        filter(max > 10000) %>% 
        left_join(trophic_modes_final_species) %>% 
        group_by(trophic_mode) %>% 
        arrange(-max) %>% 
        mutate(rank = row_number()) %>% 
        ungroup() %>% 
        arrange(-max) %>% 
        slice_head(n = 6))

quantification_sp_tmm_dfs_selectiom_sp <- 
  experiment_set_names() %>% 
  map(~ quantification_sp_tmm_dfs_sp25[[.x]] %>% 
        filter(EukProt_ID %in% sp_selection_exp[[.x]]$EukProt_ID) %>% 
        left_join(eukprot_tax %>% select(EukProt_ID, Name_to_Use)) %>% 
        left_join(trophic_modes_final_species) %>% 
        mutate(EukProt_ID = factor(EukProt_ID, levels = sp_selection_exp[[.x]]$EukProt_ID),
               Name_to_Use = 
                 case_when(
                   str_detect(Name_to_Use, 'MAST') ~ str_remove(Name_to_Use,'.*sp_'),
                   str_detect(Name_to_Use, 'Picozoa|Acanthoecidae') ~ str_replace_all(Name_to_Use,'_',' '),
                   Name_to_Use == "Mataza_sp_D1" ~ "*Mataza* sp D1",
                   Name_to_Use == "Rhizochromulina_sp_CCMP1243" ~ "*Rhizochromulina* sp CCMP1243",
                   Name_to_Use == "ChrysophyceaeNA-sp1" ~ "ChrysophyceaeNA-sp1",
                   Name_to_Use == 'Micromonas-sp1' ~ '*Micromonas*-sp1',
                   Name_to_Use == "Micromonas-sp1" ~ "Micromonas-sp1",
                   TRUE ~ paste0('*',str_replace_all(Name_to_Use,'_',' '),'*')),
               Name_to_Use = str_replace(Name_to_Use, 'sp ', 'sp. '),
               trophic_mode = factor(trophic_mode, levels = c('Heterotroph','Mixotroph','Phototroph'))) %>%
        arrange(EukProt_ID) %>% 
        mutate(Name_to_Use = factor(Name_to_Use, levels = unique(.$Name_to_Use))))

fig4_raw <- 
  experiment_set_names() %>% 
  map(~ quantification_sp_tmm_dfs_selectiom_sp[[.x]] %>% 
        left_join(metadata) %>% 
        ggplot(aes(x = as.character(round(Days)), y = Abundance/1e4)) +
        geom_col(aes(fill = trophic_mode)) +
        facet_wrap(~ Name_to_Use, scales = 'free_y', ncol = 1) +
        labs(y = NULL,
             x = NULL,
            subtitle = .x) +
        scale_fill_manual(name = '',
                          values = trophic_colors,
                          drop = FALSE)    +
        theme(strip.text = element_markdown(),
              legend.position = 'top',
              panel.grid = element_blank(),
              axis.title.y = element_markdown(),
              plot.subtitle=element_text(hjust=0.5)) +
        coord_cartesian(clip = "off"))

axis_title_y <- 
  ggplot(data = tibble(l = "Pseudocounts per million (x10<sup>4</sup>)", x = 1, y = 1)) +
  geom_richtext(aes(x, y, label = l), angle = 90, label.color = NA) + 
  theme_void() +
  coord_cartesian(clip = "off") 

axis_title_x <- 
    ggplot(data = tibble(l = "Time (days)", x = 1, y = 1)) +
  geom_richtext(aes(x, y, label = l), label.color = NA) + 
  theme_void() +
  coord_cartesian(clip = "off") 

legend <- 
  ggpubr::get_legend(fig4_raw[[1]])

fig4 <- 
  (axis_title_y +
  wrap_plots(list(fig4_raw$Mar18,fig4_raw$Jul17, fig4_raw$Sep20, fig4_raw$Nov18), nrow = 1) +
  plot_layout(widths = c(1,25)) & 
  guides(fill = 'none')) /
  axis_title_x /
  legend +
  plot_layout(heights = c(25,1,1))
  
ggsave('fig4.pdf',
       height = 12,
       width  = 10.5)
```

