---
title: "Figure 5"
author: "Aleix Obiol"
date: "2022-10-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('scripts/aux_functions.R')
```

## Read files

```{r}
annot_dir <- 'data/annotation/species52/'

annot_file <- 
  list.files(annot_dir,
             pattern = 'emapper.*\\.gz',
             full.names = T)

annotation_df <- 
  read_tsv(annot_file) %>% 
  dplyr::rename('Name' = `#query`)

quantification_sp_tmm_dfs_sp25 <-  
  readRDS('data/quantification/species52/quantification_sp-level_tmm_species25.rds')

quantification_tmm_dfs_sp25 <- 
  readRDS('data/quantification/species52/quantification_tmm_species25.rds')

eukprot_tax <- 
  read_tsv('data/aux/EukProt-v3.1_SAGs_tax.txt')
   
metadata <- 
  readRDS('data/metadata/metadata.rds')

trophic_modes_final_species <- 
  read_tsv('data/aux/species25_trophic-modes.txt')

trophic_colors <- 
  c(Heterotroph = 'darkgoldenrod1',
    Mixotroph = 'lightsalmon3',
    Phototroph = '#4AC16DFF')

clusters_peptidases <- 
  read_tsv('data/aux/peptidases_clusters.txt') %>% 
  mutate(category = 'Peptidases')

clusters_translocases <- 
  read_tsv('data/aux/translocases_clusters.txt') %>% 
  filter(str_detect(group, 'V-type') | group == 'inorganic pyrophosphatase') %>% 
  mutate(category = 'Translocases')

clusters_cazy <- 
  read_tsv('data/aux/cazy_clusters.txt') %>% 
  mutate(category = 'CAZy enzymes')

clusters_all <- 
  list(clusters_peptidases, clusters_translocases, clusters_cazy) %>% 
  bind_rows()
```

## Annotation at the KO level

```{r}
annotation_ko <- 
  annotation_df %>% 
  select(Name, KEGG_ko) %>% 
  filter(KEGG_ko != '-') %>% 
  mutate(EukProt_ID = str_remove(Name, '_.*'))
```

## Relative expression of selected enzymes

```{r}
annotation_categories <- 
  annotation_ko %>% 
  expand_annotations('KEGG_ko',simplify = F) %>% 
  left_join(clusters_all) %>% 
  select(-KEGG_ko) %>% 
  filter(!is.na(group)) %>% 
  unique() 

quantification_sp_tmm_categories_sp25 <-
  calculate_perc_categories_groups(all_df = quantification_tmm_dfs_sp25,
                            sp_df = quantification_sp_tmm_dfs_sp25)
```
## Statistical testing

```{r}
rel_expr_df <- 
  quantification_sp_tmm_categories_sp25 %>% 
  experiment_bind_rows() %>% 
  left_join(trophic_modes_final_species) %>% 
  filter(trophic_mode %in% c('Heterotroph','Phototroph')) %>% 
  ungroup() %>% 
  select(trophic_mode, perc, group) %>% 
  group_by(trophic_mode, group) %>% 
  nest() %>% 
  pivot_wider(names_from = trophic_mode,
              values_from = data)


random_test <- function(g1, g2, nreps = 10000){
  
  meanDiff <- numeric(nreps)
  n1 <-  length(g1)
  n2 <- length(g2)
  combined <- c(g1,g2)
  N <- n1 + n2
  
  set.seed(123)
  for (i in 1:nreps){
    data <- sample(combined, N,  replace = FALSE)
    grp1 <- data[1:n1]
    grp2 <- na.omit(data[n1+1: N])
    meanDiff[i] <- mean(grp1) - mean(grp2)
  }
  
  diffObt <- mean(g1) - mean(g2)
  absMeanDiff <- abs(meanDiff)
  absDiffObt = abs(diffObt)
  p.value = sum(absMeanDiff >= absDiffObt)/nreps

  return(p.value)
  
}

randomization_test <- 
  rel_expr_df %>% 
  mutate(
    random_test = map2(Heterotroph, Phototroph, ~random_test(.x$perc, .y$perc)),
    Heterotroph = map(Heterotroph, nrow),
    Phototroph = map(Phototroph, nrow)
  ) %>% 
  unnest(cols = c(Heterotroph, Phototroph, random_test))

min.obs <- 15
p.value.thres <- 0.05

total_rel_expr <- 
  rel_expr_df %>% 
  summarise(total_rel_expr_het = map_dbl(Heterotroph, ~ sum(.x)),
         total_rel_expr_phot = map_dbl(Phototroph, ~ sum(.x)))

# read table manually obtained looking at fig. 3 to know what genes had higher FC than housekeeping genes in at least 3/4 incubtions

fc_vs_hk <- 
  tibble(group = c("cysteine peptidases",
                   "serine peptidases","GT66","GT95",
                   "V-type H+-transporting ATPase subunit a","AA13","tripeptidyl-peptidase I","GH3",
                   "carboxypeptidase Z","GH20","legumain","GH18",
                   "inorganic pyrophosphatase","GT75","aspartyl peptidases",
                   "V-type H+-transporting ATPase 16kDa proteolipid subunit",
                   "V-type H+-transporting ATPase subunit B","GH7","CE10",
                   "GH13"),
     FC = c("Yes","Yes","Yes","Yes",
                       "Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","No",
                       "Yes","Yes","Yes","No","No","No","No"))

# final table

df_tests <- 
  randomization_test %>% 
  mutate(valid_test = case_when(is.na(Phototroph) ~ 'No',
                                (Heterotroph < min.obs | Phototroph < min.obs) ~ 'No',
                                TRUE ~ 'Yes'),
         signif = case_when(valid_test == 'Yes' & random_test <= p.value.thres ~ 'Yes',
                            valid_test == 'No' ~ '-',
                            TRUE ~ 'No')) %>% 
  left_join(total_rel_expr) %>%
  left_join(fc_vs_hk) %>% 
  mutate(good_candidate = case_when(FC == 'No' ~ 'No',
                                    valid_test == 'Yes' & signif == 'Yes' ~ 'Yes',
                                    Heterotroph + Phototroph < min.obs*2 ~ 'No',
                                    (Heterotroph < min.obs & Phototroph < min.obs) ~ 'No',
                                    valid_test == 'Yes' & signif == 'No' ~ 'No',
                                    TRUE ~ 'Yes'))
```


## Figure 5

```{r}
order_groups <- # from fig4
  c("cysteine peptidases", "tripeptidyl-peptidase I", "serine peptidases", "legumain", "aspartyl peptidases", "carboxypeptidase Z", "V-type H+-transporting ATPase 16kDa proteolipid subunit", "V-type H+-transporting ATPase subunit a", "inorganic pyrophosphatase", "V-type H+-transporting ATPase subunit B", "GT66", "GT75", "GH18", "GH20", "AA13", "GT95", "GH3", "GH13", "CE10", "GH7")

p_peptidases_comparison <- 
  plot_comparison_categories_trophic_mode('Peptidases', ncol = 3,nrow=2)
  
p_translocases_comparison <- 
  plot_comparison_categories_trophic_mode('Translocases', ncol = 2,nrow=2)
  
p_cazy_comparison <- 
  plot_comparison_categories_trophic_mode('CAZy enzymes', ncol = 5,nrow=2)

p1 <- p_peptidases_comparison + labs(y = 'Relative gene expression (%)')

ylab <-  
 ggplot(data.frame(l = p1$labels$y, x = 1, y = 1)) +
      geom_text(aes(x, y, label = l), angle = 90) + 
      theme_void() +
      coord_cartesian(clip = "off")

fig5_raw <- 
  ((p_peptidases_comparison | p_translocases_comparison) +
  plot_layout(widths = c(3/5,2/5))) /
  p_cazy_comparison +
  plot_layout(guides = 'collect') & 
  theme(legend.position = 'bottom') &
  scale_y_continuous(labels = scales::number_format(accuracy = 0.01))

fig5 <- 
  cowplot::plot_grid(ylab, fig5_raw,rel_widths = c(1,50))

ggsave('fig5.pdf',
       height = 10,
       width = 12)

# mark candidates genes in table 'df_tests' with Illustrator
```

